### ISSUE TITLE
Deploy to mainnet?

### ISSUE THREAD

**Issue by smeyerhot** [Vilijan/NFTMarketplace#1]
I see there is a section for deploying to testnet. What about mainnet?

**Comment by Vilijan** [comment]
In order to deploy it to mainnet not much would need to change. But you need to keep in mind that all the transaction fees and bids will need to happen with real Algos.

If you go in the `src/blockchain_utils/credentials.py` you will need to change how the client is retrieved. 

```
def get_client():
    """
    :return:
        Returns algod_client
    """
    config = load_config()

    token = config.get('client_credentials').get('token')
    address = config.get('client_credentials').get('address')
    purestake_token = {'X-Api-key': token}

    algod_client = algod.AlgodClient(token, address, headers=purestake_token)
    return algod_client
```
If you replace this function with the following one, you will be able to interact on mainnet. It uses the [algoexplorer ](https://algoexplorer.io/api-dev/v2)endpoint.
```
def get_client():
    return algod.AlgodClient("", "https://algoexplorerapi.io", headers={"User-Agent": "mainnet"})
```
